# Giornata 5: AI Generativa per la generazione di testo

In [ ]:
!pip install -U transformers

In [ ]:
from google.colab import userdata

In [ ]:
import torch

In [ ]:
#from huggingface_hub import notebook_login
#notebook_login()

## Esempio 1: Generazione di testo

### GPT2

In [ ]:
from transformers import GPT2LMHeadModel, GPT2Tokenizer

In [ ]:
MODEL_NAME = "gpt2"

In [ ]:
tokenizer = GPT2Tokenizer.from_pretrained(MODEL_NAME)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

In [ ]:
PROMPT = "How bad is a cat ?"

# Tokenize input
input_ids = tokenizer.encode(PROMPT, return_tensors="pt", add_special_tokens=True)
input_ids

tensor([[2437, 2089,  318,  257, 3797, 5633]])

In [ ]:
model = GPT2LMHeadModel.from_pretrained(MODEL_NAME)

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
output = model.generate(input_ids, max_length=100, num_return_sequences=1, no_repeat_ngram_size=2, top_k=50, top_p=0.95, temperature=0.7)
output

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:515: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:520: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[ 2437,  2089,   318,   257,  3797,  5633,   198,   198,    32,  3797,
           318,   281,  5044,   326,   318,   407,   257,  1692,   852,    13,
           632,   318,   262,   749,  2219,  2099,   286,  3797,    13,   198,
            13,   317,  3797,   460,   307,  1043,   287,   867,  1180, 35308,
            13,   383,   749,  2968,   389,   287,   262,  4295,    11,   287,
         33763,    11,   290,   287, 23629,    13, 28997,   389,   635,  1043,
           319, 15893,    11,   319,   262,  6483,    11,   393,   287, 14860,
            13,  1119,   389,  1690,  1043,   379,  1755,    11,   379,   262,
          5743,   286,   262,  1755,    13,  2773, 11875,   389,  1043,   351,
           511, 30514,  8165,  2157,   511, 12983,    13, 12691,   389,   407]])

In [ ]:
generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print(generated_text)

How bad is a cat?

A cat is an animal that is not a human being. It is the most common type of cat.
. A cat can be found in many different habitats. The most popular are in the wild, in captivity, and in shelters. Cats are also found on farms, on the streets, or in parks. They are often found at night, at the edge of the night. Some cats are found with their tails tied behind their backs. Others are not


### Gemma
 - [Repository su Hugging Face](https://huggingface.co/google/gemma-2b) ricordarsi che bisogna accettare la licenza


In [ ]:
from transformers import GemmaTokenizer, GemmaForCausalLM

In [ ]:
MODEL_NAME = "google/gemma-2b"

In [ ]:
tokenizer = GemmaTokenizer.from_pretrained(MODEL_NAME, token=userdata.get("HF_TOKEN"))

tokenizer_config.json:   0%|          | 0.00/33.6k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

In [ ]:
PROMPT = "How bad is a cat ?"

# Tokenize input
input_ids = tokenizer.encode(PROMPT, return_tensors="pt", add_special_tokens=True)
input_ids

tensor([[   2, 2299, 3338,  603,  476, 4401, 1654]])

In [ ]:
model = GemmaForCausalLM.from_pretrained(MODEL_NAME, token=userdata.get("HF_TOKEN"))

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/67.1M [00:00<?, ?B/s]

`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [ ]:
output = model.generate(input_ids, max_length=100, num_return_sequences=1, no_repeat_ngram_size=2, top_k=50, top_p=0.95, temperature=0.7)
output

tensor([[     2,   2299,   3338,    603,    476,   4401,   1654,    109, 235285,
         235303, 235262,    780,   2821,   1013,    736,    603,    573,   1833,
           2040,    577,   5291,    736,   2872, 235269,    901,    590, 235303,
            524,   1125,  20057,    604,    476,   2183,   1490, 235265,    109,
           2299,   1683,   7042,    798,    476,   4500,   4401,    749,    577,
            476,   3515,   1654,    590,   2714, 235269,    590,   1230,    674,
          19493,    798,   9451,    476,   1552, 235269,    578,    590,   1170,
           1230,   1368,    577,   9051,   6836,    774,    476,  26911, 235269,
            689,    476,  24935, 235269,   3687, 235265,   2005,    590,    729,
          20057,   1013,    476,   5748,   4401,    798,    749,    476,   2940,
            576,   7042,    577,    573,   3515,   2971, 235265,    590,   1453,
         235303]])

In [ ]:
generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print(generated_text)

How bad is a cat ?

I'm not sure if this is the right place to ask this question, but I've been wondering for a while now.

How much damage can a normal cat do to a human ? I mean, I know that cats can kill a person, and I also know how to protect myself from a bite, or a scratch, etc. But I was wondering if a regular cat can do a lot of damage to the human body. I don'


### Minerva

 - [Repository su Hugging Face](https://huggingface.co/sapienzanlp/Minerva-1B-base-v1.0) ricordarsi che bisogna accettare la licenza

In [ ]:
from transformers import AutoTokenizer, MistralForCausalLM

In [ ]:
MODEL_NAME = "sapienzanlp/Minerva-1B-base-v1.0"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, token=userdata.get("HF_TOKEN"))

In [ ]:
PROMPT = "Quanto è cattivo un gatto ?"

# Tokenize input
input_ids = tokenizer.encode(PROMPT, return_tensors="pt", add_special_tokens=True)
input_ids

tensor([[    1, 11938,   413, 21972,   329, 17935,  5138]])

In [ ]:
model = MistralForCausalLM.from_pretrained(MODEL_NAME, token=userdata.get("HF_TOKEN"))

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
output = model.generate(input_ids, max_length=100, num_return_sequences=1, no_repeat_ngram_size=2, top_k=50, top_p=0.95, temperature=0.7)
output

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:515: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:520: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


tensor([[    1, 11938,   413, 21972,   329, 17935,  5138,   478, 12195, 32347,
         32381,   478,  7404,   294, 27728,   294, 20769, 23551, 32367,   275,
            13, 30785,  1286,   439,  4489,   439,   337, 32367, 32378, 32367,
          2125, 10022, 32347, 32380, 32380,  3988, 32347, 32377, 32408, 32368,
         32347, 32408, 32393, 32403, 32377,    13, 32383, 32367,   321, 32367,
           403,  4405, 32393,  1380,   413,   360,   459,  1452,  4418,   356,
         17935, 32368,   413,  1063,   360,   413,   329, 17657,   360,  1452,
          1030,  8016,  4673, 32367,    13,  6916,   413,  3710, 32368,   459,
           413,  1584, 32367,   635, 17935,   413,   456,   711,  1732,   360,
           403,  3695,   294,   846, 29362, 32368, 28624,  1411,   455, 32368]])

In [ ]:
generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print(generated_text)

Quanto è cattivo un gatto ? - Pagina 2 - Forum di Psicologia di Nienteansia.it
Messaggio da leggere da M.T. » mercoledì 11 aprile 09, 9:50
M. T. ha scritto: Non è che non ti piace il gatto, è solo che è un animale che ti fa stare male.
Non è vero, non è così. Il gatto è una creatura che ha bisogno di essere amata, coccolata,


## Esempio 2: Generazione di codice Python
 - [Repository su Hugging Face](https://huggingface.co/codellama/CodeLlama-7b-hf)

In [ ]:
!pip install accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.6/302.6 kB 7.7 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

In [ ]:
from transformers import AutoTokenizer
import transformers
import torch

In [ ]:
MODEL_NAME = "codellama/CodeLlama-7b-hf"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

In [ ]:
pipeline = transformers.pipeline(
    "text-generation",
    model=MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto",
)

config.json:   0%|          | 0.00/637 [00:00<?, ?B/s]

ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

In [ ]:
prompt = "def hello_world():"

In [ ]:
def generate_code(prompt):
    output = pipeline(
        prompt,
        do_sample=True,
        temperature=0.1,
        top_p=0.9,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        max_length=128,
    )
    print(output[0]["generated_text"])


generate_code(prompt)

## Esempio 3: Generazione di traduzioni
 - [Repository su HuggingFace](https://huggingface.co/Helsinki-NLP/opus-mt-it-en)
 - [Documentazione MarianMTModel](https://huggingface.co/docs/transformers/model_doc/marian)

In [ ]:
from transformers import AutoTokenizer, MarianMTModel

In [ ]:
SOURCE = "it"
TARGET = "en"

MODEL_NAME = f"Helsinki-NLP/opus-mt-{SOURCE}-{TARGET}"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = MarianMTModel.from_pretrained(MODEL_NAME)

In [ ]:
prompt = "I gatti sono cattive persone"

In [ ]:
input_ids = tokenizer.encode(PROMPT, return_tensors="pt")
output = model.generate(input_ids)
translation = tokenizer.decode(output[0], skip_special_tokens=True)
print(translation)

In [ ]:
batch = tokenizer([prompt], return_tensors="pt")
generated_ids = model.generate(**batch)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]